In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets
mnist=datasets.load_digits()

In [3]:
x=mnist.data
y=mnist.target

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=63)
x_train_pca = pca.fit_transform(x_train)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\Users\Mukul\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mukul\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [8]:
y_pred = classifier.predict(x_test)

In [9]:
from sklearn.metrics import confusion_matrix, classification_report

In [10]:
print( "Accuracy score: ", classifier.score(x_test, y_test))

Accuracy score:  0.9537037037037037


In [11]:
print( "Confusion matrix: \n", confusion_matrix(y_test, y_pred))

Confusion matrix: 
 [[45  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  1  0  2  0]
 [ 0  2 50  1  0  0  0  0  0  0]
 [ 0  0  1 52  0  0  0  0  1  0]
 [ 0  0  0  0 47  0  0  1  0  0]
 [ 0  1  0  0  0 55  1  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  0  0  2  0  0  0 51  0  0]
 [ 0  4  1  1  0  0  1  0 53  1]
 [ 0  0  0  0  0  2  0  1  0 54]]


In [12]:
print ("Classification Report: \n", classification_report(y_test, y_pred))

Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       0.86      0.94      0.90        52
           2       0.96      0.94      0.95        53
           3       0.93      0.96      0.95        54
           4       1.00      0.98      0.99        48
           5       0.96      0.96      0.96        57
           6       0.95      0.98      0.97        60
           7       0.96      0.96      0.96        53
           8       0.95      0.87      0.91        61
           9       0.98      0.95      0.96        57

   micro avg       0.95      0.95      0.95       540
   macro avg       0.96      0.96      0.96       540
weighted avg       0.95      0.95      0.95       540

